### ISSUE TITLE
Exe not running

### ISSUE THREAD

**Issue by rin-ikagari** [Astrioa/TheHungerOfGawrGura#1]
Hello, I apologize if this a error from my side, but when I try to run the exe, nothing happens, I don't know what I'm doing wrong, thank you very much.

**Comment by Astrioa** [comment]
Do you know the directory/location? The exes in the source dont run the game, it needs to be compiled by packaging it in UE4 to get an exe.

![image](https://user-images.githubusercontent.com/76748414/119212418-c690f880-ba7d-11eb-8f4d-e0a48c9f1870.png)

**Comment by rin-ikagari** [comment]
Understood, thank you very much.
